# fly.toml app configuration file generated for serwisownik on 2025-08-02T19:30:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#


app = 'serwisownik'
primary_region = 'waw'




[[vm]]
 memory = '1gb'
 cpu_kind = 'shared'
 cpus = 1


[build]
 dockerfile = "docker/php/Dockerfile"


[env]
 APP_ENV = "prod"


[[services]]
 internal_port = 8080
 protocol = "tcp"


 [[services.ports]]
   handlers = ["http"]
   port = 80


 [[services.ports]]
   handlers = ["tls", "http"]
   port = 443
