version: '3.8'


services:
 php:
   build:
     context: ./php
   volumes:
     - ../backend:/var/www/html
   working_dir: /var/www/html
   environment:
     - APP_ENV=dev
   depends_on:
     - frontend


 nginx:
   image: nginx:latest
   ports:
     - "8080:80"
   volumes:
     - ../backend/public:/var/www/html/public
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
     - ../frontend/dist:/var/www/html/public/build
   depends_on:
     - php


 frontend:
   image: node:20-alpine3.22
   working_dir: /app
   volumes:
     - ../frontend:/app
   command: sh -c "npm install && npm run build"


